# docker-compose.yml
version: "3"

# volumes:
#   PostgresData:

services:
  yard-sales-api:
    container_name: yard-sales-api
    build: .
    depends_on:
      - yard-sales-postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      PORT: 8000
      DB_PORT: 5432
      DB_USERNAME: db_access
      DB_PASSWORD: freedom
      DB_NAME: yard-sales
      DB_HOST: postgresDB
      NODE_ENV: development
      PORT: 8000
    ports:
      - "8000:8000"
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  yard-sales-postgres:
    container_name: yard-sales-postgres
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: docker
    volumes:
      - PostgresData:/var/lib/postgresql/data