# docker-compose.yml
version: "3"

volumes:
  PostgresData:

services:
  db:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
    volumes:
      - PostgresData:/var/lib/postgresql/data

  api:
    build: ./
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file: ./.env
    ports:
      - "8000:8000"
    command: npm run dev
